name: CI for monorepo
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Cache bazel
        uses: actions/cache@v3
        with:
          path: ~/.cache/bazel
          # If any of these files are changed, we invalidate the cache
          key: ${{ runner.os }}-bazel-${{ hashFiles('.bazeliskrc', '.bazelrc', 'WORKSPACE.bazel') }}
          restore-keys: |
            ${{ runner.os }}-bazel-

      # TODO: only build changed files
      - name: Build
        run: make build
